#PREPARATIVOS DEL ESPACIO DE TRABAJO

In [4]:
# Montar Google Drive para acceder a los archivos de la carpeta
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [5]:
import os
# Modifica la siguiente instrucción si guardaste la carpeta
# en una ubicación diferente a "My Drive"
folder_path ='/content/drive/MyDrive/DATA ANALYST PORTFOLIO/LIMPIEZA DE DATOS'
os.chdir(folder_path) # Change directory
print("Nuevo directorio de trabajo: ")
!pwd

Nuevo directorio de trabajo:
/content/drive/MyDrive/DATA ANALYST PORTFOLIO/LIMPIEZA DE DATOS

In [6]:
!pip install pandas
!pip install pandas-datareader

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (2.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2023.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.1)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.25.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: pandas-datareader in /usr/local/lib/python3.10/dist-packages (0.10.0)
Requirement already satisfied: lxml in /usr/local/lib/python3.10/dist-packages (from pandas-datareader) (4.9.4)
Requirement already satisfied: pandas>=0.23 in /usr/local/lib/python3.10/dist-packages (from pandas-datareader) (2.0.3)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.10/dist-packages (from pandas-datareader) (2.31.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.23->pandas-datareader) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.23->pandas-datareader) (2023.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.23->pandas-datareader) (2024.1)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.23->pandas-datareader) (1.25.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->pandas-datareader) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->pandas-datareader) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->pandas-datareader) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->pandas-datareader) (2024.6.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas>=0.23->pandas-datareader) (1.16.0)

In [7]:
# Importo las librerias que usaré
import numpy as np
import pandas as pd
from random import sample
import random as random
from datetime import date

In [8]:
#Leo el archivo
filename = 'reporte_datos_final.csv'
df_principal = pd.read_csv(filename)
df_principal.head(5)
df_principal.shape

(20808, 10)

#Trabajo con los datos

In [9]:
# Voy a leer la tabla con los estados desde una URL
url = 'https://es.wikipedia.org/wiki/Estado_de_los_Estados_Unidos'
df_estados = pd.read_html(url)
df_estados = df_estados[1] #Obtengo la tabla donde estan todos los estados que necesito
lista_estados = df_estados['Estado'].to_numpy().transpose().tolist()

In [10]:
#Agrego una nueva columna en el dataFrame principal usando Random Choice
#Si tiene un contrato hibrido se deja el valor siempre para Texas, en caso de remoto toma un valor de la lista de estados aleatoriamente
estado = 'Texas'
df_principal['States'] = df_principal['type'].apply(lambda x: estado if x == 'HYBRID' else np.random.choice(lista_estados))

# Limpio caracteres especiales y números de la columna 'States'
df_principal['States'] = df_principal['States'].str.replace(r'\[.*?\]', '', regex=True).str.replace(r'\d+', '', regex=True)

In [14]:
#Calculo la edad de cada trabajador
df_principal['birth_date'] = pd.to_datetime(df_principal['birth_date']).dt.date
df_principal['Age'] = df_principal['birth_date'].apply(lambda x: date.today().year - x.year - ((date.today().month, date.today().day) < (x.month, x.day)))
df_principal.head(5)

,Id_emp,Name,Last_name,birth_date,gender,area,salary,email,start_date,type,States,Age
0,41-2225304,Ezekiel,A'Barrow,1999-02-18,male,Business Development,80709,Ezekiel_A'.R@example.com,2001-08-07,REMOTE,Nevada,25
1,01-0027092,Jock,Aarons,1988-12-23,female,Engineering,173688,Jock_Aa.R@example.com,2002-08-11,REMOTE,Nueva Jersey​,35
2,82-2860536,Ferrel,Aartsen,1995-07-13,female,Accounting,117511,Ferrel_Aa.H@example.com,2016-06-03,HYBRID,Texas,28
3,18-0367857,Marge,Abate,1973-03-25,female,Engineering,112662,Marge_Ab.H@example.com,2007-01-26,HYBRID,Texas,51
4,76-7456746,Ado,Abatelli,1975-10-27,male,Accounting,84683,Ado_Ab.H@example.com,2014-01-24,HYBRID,Texas,48

In [15]:
df_principal.head(35)

,Id_emp,Name,Last_name,birth_date,gender,area,salary,email,start_date,type,States,Age
0,41-2225304,Ezekiel,A'Barrow,1999-02-18,male,Business Development,80709,Ezekiel_A'.R@example.com,2001-08-07,REMOTE,Nevada,25
1,01-0027092,Jock,Aarons,1988-12-23,female,Engineering,173688,Jock_Aa.R@example.com,2002-08-11,REMOTE,Nueva Jersey​,35
2,82-2860536,Ferrel,Aartsen,1995-07-13,female,Accounting,117511,Ferrel_Aa.H@example.com,2016-06-03,HYBRID,Texas,28
3,18-0367857,Marge,Abate,1973-03-25,female,Engineering,112662,Marge_Ab.H@example.com,2007-01-26,HYBRID,Texas,51
4,76-7456746,Ado,Abatelli,1975-10-27,male,Accounting,84683,Ado_Ab.H@example.com,2014-01-24,HYBRID,Texas,48
5,35-4558116,Lisa,Abatelli,1980-03-19,female,Accounting,116635,Lisa_Ab.H@example.com,2013-09-10,HYBRID,Texas,44
6,76-2607804,Stoddard,Abatelli,1975-07-29,female,Human Resources,107894,Stoddard_Ab.R@example.com,2014-08-03,REMOTE,Georgia,48
7,02-7423004,Sharleen,Abba,1994-02-04,female,Engineering,173241,Sharleen_Ab.H@example.com,2020-07-31,HYBRID,Texas,30
8,52-1535671,Annabel,Abbado,2001-10-04,male,Human Resources,114137,Annabel_Ab.H@example.com,2010-03-29,HYBRID,Texas,22
9,65-9379141,Sandy,Abbey,1995-08-07,female,Business Development,89591,Sandy_Ab.R@example.com,2007-03-06,REMOTE,Carolina del Norte,28
10,46-6951486,Tim,Abbie,1999-09-07,female,Business Development,94796,Tim_Ab.H@example.com,2016-12-11,HYBRID,Texas,24
11,03-5122131,Gladi,Abbot,1974-12-03,male,Accounting,149717,Gladi_Ab.R@example.com,2017-09-07,REMOTE,Carolina del Sur,49
12,05-2710257,Laurence,Abbot,2002-07-09,female,Engineering,137187,Laurence_Ab.H@example.com,2002-09-22,HYBRID,Texas,21
13,05-6984388,Vittoria,Abbots,1972-10-28,male,Engineering,138509,Vittoria_Ab.H@example.com,2014-06-03,HYBRID,Texas,51
14,21-0225498,Shellysheldon,Abbott,2002-03-02,female,Accounting,78880,Shellysheldon_Ab.R@example.com,2015-06-26,REMOTE,Dakota del Norte,22
15,30-8756028,Weider,Abby,1995-07-24,female,Human Resources,181803,Weider_Ab.R@example.com,2003-09-01,REMOTE,Iowa,28
16,52-9799598,Leticia,Abbys,1997-01-31,male,Engineering,175563,Leticia_Ab.R@example.com,2003-10-26,REMOTE,Delaware,27
17,40-4809866,Wayland,Abeau,1978-09-04,male,Engineering,179529,Wayland_Ab.R@example.com,2004-06-01,REMOTE,Arkansas,45
18,09-6007498,Daryl,Abeau,1975-08-09,female,Human Resources,157066,Daryl_Ab.H@example.com,2012-02-16,HYBRID,Texas,48
19,37-6038275,Lucienne,Abela,1992-06-26,female,Support,80599,Lucienne_Ab.R@example.com,2008-01-08,REMOTE,Wyoming,31
20,44-7890623,Hope,Abeles,1978-01-25,female,Engineering,116571,Hope_Ab.H@example.com,2011-11-10,HYBRID,Texas,46
21,59-6588155,Waldo,Abelov,1975-07-17,male,Product Management,77546,Waldo_Ab.H@example.com,2011-02-07,HYBRID,Texas,48
22,03-6259593,Sophey,Abelson,1978-06-21,male,Research and Development,158580,Sophey_Ab.R@example.com,2000-11-11,REMOTE,Nuevo México​,45
23,54-4029541,Domingo,Abendroth,1982-01-29,female,Product Management,73828,Domingo_Ab.H@example.com,2009-06-18,HYBRID,Texas,42
24,77-6125082,Goraud,Aberchirder,1995-11-15,female,Training,151781,Goraud_Ab.R@example.com,2011-04-28,REMOTE,Arizona,28
25,61-6204991,Esma,Aberdalgy,1986-11-01,female,Engineering,176250,Esma_Ab.H@example.com,2018-02-05,HYBRID,Texas,37
26,29-0125171,Hildegaard,Aberdein,2000-08-25,male,Sales,105387,Hildegaard_Ab.R@example.com,2006-09-13,REMOTE,Washington,23
27,17-7474380,Wren,Aberhart,1983-09-23,male,Accounting,183083,Wren_Ab.R@example.com,2020-09-24,REMOTE,Wyoming,40
28,61-6008733,Meade,Aberhart,1970-07-27,female,Business Development,75134,Meade_Ab.H@example.com,2012-01-17,HYBRID,Texas,53
29,81-4119257,Issi,Abernethy,1974-08-20,male,Human Resources,82631,Issi_Ab.R@example.com,2013-05-04,REMOTE,Arkansas,49
30,25-6983034,Donelle,Ableson,1974-02-08,male,Engineering,131108,Donelle_Ab.H@example.com,2014-08-19,HYBRID,Texas,50
31,67-8358027,Uri,Ableson,1974-03-28,male,Legal,143576,Uri_Ab.R@example.com,2013-11-06,REMOTE,Misuri​,50
32,52-9368890,Joe,Ablett,1966-01-23,male,Engineering,172940,Joe_Ab.R@example.com,2003-04-22,REMOTE,Misuri​,58
33,18-0527111,Gonzalo,Ablewhite,1969-04-28,male,Research and Development,137336,Gonzalo_Ab.R@example.com,2002-12-09,REMOTE,Colorado,55
34,45-2863542,Rona,Abraham,1977-03-02,male,Human Resources,81414,Rona_Ab.R@example.com,2007-08-23,REMOTE,Florida,47

#Exportamos el documento con la fila que agregamos

In [16]:
df_principal.to_csv('Report_Tableau.csv')